version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tournament
  social-tournament-service:
    build: .
    image: sergiydagunov/social-tournament-service:latest
    restart: always
    environment:
      - POST=5000
      - LOG_LEVEL=verbose
      - STAGE=master
      - POSTGRES_HOST=db
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tournament
    ports:
      - 80:5000
    command: sh -c './wait-for && sequelize db:migrate && npm start'
    depends_on:
      - db
